---
language: python
python: "2.7"

services:
  - docker

install:
  - pip install --upgrade pip
  - curl https://raw.githubusercontent.com/timorunge/docker-test-runner/master/install.sh | sh

script:
  - ./docker_test_runner.py
