---
language: python
python: "2.7"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      env: ANSIBLE_VERSION='ansible>=2.4,<2.5'
    - os: linux
      dist: trusty
      sudo: true
      env: ANSIBLE_VERSION='ansible>=2.3,<2.4'
    - os: linux
      dist: trusty
      sudo: true
      env: ANSIBLE_VERSION='latest'
    - os: linux
      dist: xenial
      sudo: true
      env: ANSIBLE_VERSION='ansible>=2.4,<2.5'
    - os: linux
      dist: xenial
      sudo: true
      env: ANSIBLE_VERSION='ansible>=2.3,<2.4'
    - os: linux
      dist: xenial
      sudo: true
      env: ANSIBLE_VERSION='latest'

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install $ANSIBLE_VERSION; fi
  # Check ansible version
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Full install check
  - ansible-playbook tests/test.yml -i tests/inventory -v
	# Impotence check
  - ansible-playbook tests/test.yml -i tests/inventory -v | grep -q 'changed0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
