---

- name: "Spark: symlink to common dirs"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "{{ spark_path }}/conf/", dest: /etc/spark }
    #- { src: "{{ spark_path }}/log/", dest: /var/log/spark }
  become: true

- name: "Spark: set spark environment variables"
  template:
    src: spark-env.sh.j2
    dest: "{{ spark_path }}/conf/spark-env.sh"
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"
  notify:
    - spark-master restart
    - spark-worker restart
  become: true

# Create services
- name: "Spark: create systemd script for master"
  template:
    src: spark-master.service.j2
    dest: "{{ spark_systemd_dir }}/spark-master.service"
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"
  notify:
    - spark-master restart
  become: true

- name: "Spark: create systemd script for worker"
  template:
    src: spark-worker.service.j2
    dest: "{{ spark_systemd_dir }}/spark-worker.service"
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"
  notify:
    - spark-worker restart
  become: true
  when: spark_worker_enabled == "yes"
    

- name: "Spark: ensure spark-master service is enabled and running"
  service:
    name: spark-master
    enabled: "{{ spark_master_enabled }}"
  become: true
  when: spark_master_enabled == "yes"

- name: "Spark: ensure spark-worker service is enabled and running"
  service:
    name: spark-worker
    enabled: "{{ spark_worker_enabled }}"
  become: true
  when: spark_worker_enabled == "yes"
