---

- name: "Spark: symlink to common dirs"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "{{ spark_path }}/conf/", dest: /etc/spark }
    - { src: "{{ spark_path }}/log/", dest: /var/log/spark }

- name: "Spark: set spark environment variables"
  template:
    src: spark-env.sh.j2
    dest: "{{ spark_path }}/conf/spark-env.sh"
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"
  notify:
    - spark-master restart
    - spark-worker restart

# Create services
- name: "Spark: create systemd script for master"
  template:
    src: spark-master.service.j2
    dest: "{{ spark_systemd_dir }}/spark-master.service"
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"

- name: "Spark: create systemd script for worker"
  template:
    src: spark-worker.service.j2
    dest: "{{ spark_systemd_dir }}/spark-worker.service"
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"

