---

- name: "Spark: fetch source"
  get_url:
    url: "{{ spark_download_url }}"
    dest: "/usr/local/src/{{ spark_bin_name }}"
  become: true

- name: "Spark: create install directory"
  file:
    path: "{{ spark_path }}"
    state: directory
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"
    recurse: yes
  become: true

- name: "Spark: unarchive donwloaded package"
  unarchive:
    src: "/usr/local/src/{{ spark_bin_name }}"
    dest: "{{ spark_path }}"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
  become: true
