---

- name: "Spark: download package"
  command: "/usr/bin/wget  {{ spark_download_path }}"
  args:
    chdir: /tmp
    creates: "/tmp/{{ spark_bin_name }}"

- name: "Spark: create install directory"
  file:
    path: "{{ spark_install_dir }}"
    state: directory
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"

- name: "Spark: unarchive donwloaded package"
  unarchive:
    src: "/tmp/{{ spark_bin_name }}"
    dest: "{{ spark_install_dir }}"

