---

- name: "Spark: create Spark group"
  group:
    name: "{{ spark_group }}"

- name: "Spark: create Spark user"
  user:
    name: "{{ spark_user }}"
    group: "{{ spark_group }}"

- include: install.yml

- include: configure.yml
