---

- name: "Spark: create Spark group"
  group:
    name: "{{ spark_group }}"
  become: true

- name: "Spark: create Spark user"
  user:
    name: "{{ spark_user }}"
    group: "{{ spark_group }}"
  become: true

- include_tasks: install.yml

- include_tasks: configure.yml
