---

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"
  become: true

- name: spark-master restart
  service:
    name: spark-master
    state: restarted
  become: true
  when: spark_master_enabled != "no"

- name: spark-worker restart
  service:
    name: spark-worker
    state: restarted
  become: true
  when: spark_worker_enabled != "no"
