---

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: spark-master restart
  service:
    name: spark-master
    state: restarted

- name: spark-worker restart
  service:
    name: spark-worker
    state: restarted

